### ISSUE TITLE
Microsoft Computer Vision API key found in source

### ISSUE THREAD

**Issue by johnbindel** [kphillpotts/ImageSearch-Cognitive#1]
https://github.com/kphillpotts/ImageSearch-Cognitive/blob/81aadffc625745b26cce801ca55100620d9b4b87/ImageSearch/ImageSearch/Analyze.cs

Since the key is checked into public github, _anyone can see/use it_. Consider taking the following steps to remedy this:
1. get a new API key (Azure Portal -> Cognitive Services -> Resource Management (Keys) -> Regenerate)
2. retire usage of key
3. do this with config that is not-version controlled- don't check the new key(s) into GitHub

**Comment by kphillpotts** [comment]
Done and done!
